name: section7
description: "module 7 of flutter course dr yu"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Updated to latest version available
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Updated to latest lint package
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - images/
